import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import SideNavigation from "@/components/v1/SideNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row w-screen h-screen`}>
        <SideNavigation />
        {children}
      </body>
    </html>
  );
}
